---
- name: Deploying Satellite Key for Remote Execution
  hosts: all
  tasks:
    - name: Ensuring the key exists
      ansible.posix.authorized_key:
        user: ec2-user
        key: "{{ lookup('url', 'https://{{ sat6_fqdn }}:9090/ssh/pubkey', split_lines=False, validate_certs=False) }}"
        state: present
