---
  - name: Unregistering {{ target_hostname }} from Satellite and Insights
    hosts: "{{ target_hostname }}"
    # become: true

    tasks:
    - name: Unregister {{ target_hostname }} from Insights
      ansible.builtin.command: insights-client --unregister
      register: output
      changed_when: "'Successfully unregistered from the Red Hat Insights Service' in output.stdout"

    - name: Unregistering {{ target_hostname }} from {{ sat6_fqdn }}
      redhat_subscription:
        state: absent
        activationkey: "{{ activation_key }}"
        org_id: "{{ org_id }}"

