---
  - name: yum update
    hosts: "{{ target_hostname }}"
    become: true

    tasks:

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    # - name: Updating yum packages on {{ target_hostname }}
    #   ansible.builtin.command: yum update --assumeyes