---
- name: update vulnerable packages
  hosts: all
#  vars:
#    cve_list: "--cve CVE-2019-18276 --cve CVE-2021-23240"
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q {{ cve_list | regex_search('(--cve (CVE-[0-9]{4}-[0-9]+)\\s*)+') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100
      args:
        warn: false

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} upgrade -v -y {{ cve_list | regex_search('(--cve (CVE-[0-9]{4}-[0-9]+)\\s*)+') }}"
      args:
        warn: false

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        needs_reboot: true


- name: Reboot system (if applicable)
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - when:
        - needs_reboot is defined
        - needs_reboot
      block:
        - name: Reboot system
          shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
          async: 1
          poll: 0
